### ISSUE TITLE
ImageAlpha not working when running ImageOptim-CLI

### ISSUE THREAD

**Issue by Trullus** [JamieMason/ImageOptim-CLI#95] opened 2014-11-05 16:19 UTC
Hello!

First of all, thank you very much for your great work. I got an issue and hoping to find some answers.

When running ImageOptim-CLI the script outputs "Running ImageAlpha..." but immediately jumps to "Running ImageOptim...". I originally thought, that the scirpt is just really fast, but then i ran some tests.

I copied my image folder and ran the script on one folder without, and afterwards on the other folder with the option for ImageAlpha. The result was, that the file size of all images in both folders were identical. I afterwards ran ImageAlpha manually on some of the files, and had some huge gains.

After reading some older issues I checked the location of ImageAlpha, but it was installed in the right directory (/Applications/). I tried to reinstall ImageAlpha, but it didn't resolve the issue. Interestingly the script didn't output any error, when i ran it with the option to use ImageAlpha without the tool installed.

My specs are:
OS X Yosemite 10.10
ImageOptim-CLI 1.11.4
ImageAlpha 1.3.5
ImageOptim 1.5.4-yosemite

Thanks in advance.

**Comment by JamieMason** [comment] 2015-01-05 08:27
Thanks @fbbarros, I'm working on a v2 locally and this extra configuration will be part of it.

Regarding whether ImageAlpha is running @Trullus, I'm sure that it is but because the quality is set quite high it's very often the case that images are skipped because the proposed optimisation is larger. I have seen locally when lowering this range that images are changed more often. I will close this for that reason.

**Comment by falzhobel** [comment] 2015-02-10 00:31
Hey guys, I'm getting a similar issue while running the CLI on 2 PNG files that are quite large :+1: 

![1__guillaume_guillaumes-macbook-air____downloads_fermieres__zsh_](https://cloud.githubusercontent.com/assets/136990/6119017/8c8270d0-b091-11e4-94ea-3ceef89fade3.png)

Here's what I get when running them the ImageAlpha app : 

![09_7_item_recipe1_png_and_11_3_item_yarn_png_and_epoque4-2_and_epoque4-2](https://cloud.githubusercontent.com/assets/136990/6119064/126bbeae-b092-11e4-8f97-efe19f8bbfbb.jpg)

The CLI worked perfectly for the 74 other images I had (.png and .jpg)

**Comment by JamieMason** [comment] 2015-02-12 19:16
Reopening so I don't miss this @falzhobel.

**Comment by scttcper** [comment] 2015-04-09 17:09
I'm getting something similar.

Running ImageAlpha...
find: /var/folders/12/qfs4md7x73b1vrrz89hxhhtr0000gn/T//imageoptim-cli/png: No such file or directory
Running ImageOptim...

Skips over ImageAlpha once it decides it is not found. I have tried:
Reinstalling ImageAlpha (current newest version)
rm -rf the //imageoptim folder
Using node 0.12.2 and iojs v1.6.3

I'm on Yosemite 10.10.3. Let me know what else I could try.

**Comment by falzhobel** [comment] 2015-04-09 17:35
Thanks @JamieMason !

**Comment by JamieMason** [comment] 2015-12-23 12:41
Closing as duplicate of #68.

**Closed by JamieMason** 2015-12-23 12:41 UTC
Labels: can't reproduce
