### ISSUE TITLE
Installed by npm, but command not found

### ISSUE THREAD

**Issue by longvo55** [JamieMason/ImageOptim-CLI#132] opened 2017-01-22 04:02 UTC
I have downloaded ImageOptim (https://imageoptim.com/mac) ImageAlpha (https://pngmini.com) and JPEGMini Pro, they're all in my Applications, added JPEGMini Pro to Accessibility . Then I installed ImageOptim-CLI via npm install -g imageoptim-cli. When I ran the command imageoptim I get:
-bash: imageoptim: command not found

echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

I am on macOS Sierra 10.12.2

**Comment by JamieMason** [comment] 2017-01-22 11:51
are you able to install and use other npm global packages? `npm install -g npm-check-updates` then `ncu --version` for example.

**Comment by pablonnaoji** [comment] 2017-01-26 01:02
@JamieMason Im also having the same issue as longvo55. When I install npm-check-updates to test I get an accurate version (2.8.9). Is there a fix for this npm install issue?

**Comment by pablonnaoji** [comment] 2017-01-27 17:42
If your running this on a Linux server - as I was - server compatibility may be the issue here.

**Comment by JamieMason** [comment] 2017-01-30 10:34
Thanks @pablonnaoji, I suspect that might be a different issue to @longvo55 though? with @longvo55 using OSX.

**Comment by JamieMason** [comment] 2017-01-30 15:49
Please re-open when you have more info @longvo55 and we'll be happy to help 👍

**Closed by JamieMason** 2017-01-30 15:49 UTC
Labels: Type: Question

**Comment by neikei** [comment] 2017-02-28 08:25
I had the same issue and found the root cause for my Debian 8.7 server. You have to start the commandline tool with an upper O in the name. Check the following example:

`root@lemp-playground:~# imageoptim -v
-su: imageoptim: command not found
root@lemp-playground:~# imageOptim -v
1.14.8`

**Comment by jcklpe** [comment] 2018-11-28 08:48
Does this utility not work on linux?

**Comment by neikei** [comment] 2018-11-28 09:32
I don't think so, because this tool calls only three different MacOS tools. 

But my test a year ago was only rudimentary.
