### ISSUE TITLE
Run With ImageAlpha, not working.

### ISSUE THREAD

**Issue by evercry** [JamieMason/ImageOptim-CLI#117] opened 2015-09-07 06:17 UTC
$ imageOptim -a -d ./
Running ImageAlpha...
find: /var/folders/f1/tsx0lwz55r714813288mldhr0000gn/T//imageoptim-cli/png: No such file or directory
Running ImageOptim...
.//resource.jpg was: 136.316kb now: 136.316kb saving: 0kb (0%)
TOTAL was: 136.316kb now: 136.316kb saving: 0kb (0%)

Please check this.

**Comment by JamieMason** [comment] 2015-12-23 12:30
Thanks @evercry, closing as duplicate of #68, which I have reopened.

**Closed by JamieMason** 2015-12-23 12:30 UTC
