### ISSUE TITLE
Timeout on JPEGmini with a lot of files

### ISSUE THREAD

**Issue by GregOriol** [JamieMason/ImageOptim-CLI#108] opened 2015-02-18 18:27 UTC
Trying to pass a lot of files through JPEGmini + ImageOptim, I had a timeout and ImageOptim-cli went to the next step, while the first one wasn't over; which broken somehow the process:

```
Running JPEGmini...
/usr/local/bin/imageOptimAppleScriptLib:5093:5097: execution error: JPEGmini got an error: AppleEvent timed out. (-1712)
Running ImageOptim...
```

Maybe a longer time on AppleScript could be used somehow?

**Comment by JamieMason** [comment] 2015-12-23 12:33
Thanks for this @GregOriol and sorry for the delay — could you tell me how many images you were running over so I can attempt to reproduce?

**Comment by GregOriol** [comment] 2015-12-23 12:40
Well, I don't remember exactly how many files, it was a long time ago (in a galaxy far far away), could have been like 2000

I read this about AppleScript timeouts: http://stackoverflow.com/questions/22446276/applescript-apple-event-timed-out => seems to have a default value of 2min, maybe it could be extended depending on the number of files? (number of files * 5sec ?)

**Comment by JamieMason** [comment] 2015-12-23 12:45
Thanks @GregOriol, that link is really useful and the exact number wasn't important, just a ballpark figure.

**Comment by JamieMason** [comment] 2017-01-17 16:42
One approach could be to bundle the files into batches then process each bundle at a time, to limit the load on the .apps.

**Comment by JamieMason** [comment] 2018-12-23 18:01
Closing as the project has had a rewrite since this issue was created a long time ago. Anyone running into this issue please feel free to reopen it.

**Closed by JamieMason** 2018-12-23 18:01 UTC
Labels: Priority: Low, Status: To Do, Type: Fix
